### ISSUE TITLE
Waku Is Uncompromising Web3 Communication at Scale

### ISSUE THREAD

**Issue by Sergei-Mak** [waku-org/bounties#20]
## Context

Waku Is Uncompromising Web3 Communication at Scale.
A family of robust, censorship-resistant communication protocols, designed to enable privacy-focused messaging for web3 apps.

The JavaScript implementation of Waku, [js-waku](https://github.com/waku-org/js-waku/), enables web apps to utilize the Waku network for off-chain message transmission.

Disclaimer: Waku is **experimental**, you may find blocking issues while developing your web app. We will prioritize their resolution to unblock you, which means you may have to pause development until done.
Thank you for your patience and understanding.

**Your participation in this bounty is subject to your acceptance of our terms and conditions.**
Please see waku-org/bounties#applying-for-a-bounty for details.

## Rewards

XXX DAI

## Timeframe to Completion

Once the application is approved, the result must be submitted within 30 days.

## Application Evaluation

To ensure you are selected for this bounty, provide the following information:

- Describe the approach you will take to tackle the bounty.
- A timeline within which you expect to deliver the bounty.
- Any previous relevant work you have done.

### Acceptance Criteria

- Must contain instructions on how to build and run the software.

### Resources

Learn more about Waku at https://docs.waku.org/.
Join our Discord to get support at https://discord.waku.org/.
Various examples available at https://github.com/waku-org/js-waku-examples/.

**Comment by chair28980** [comment]
@Sergei-Mak Hello there! I just want to clarify if you intended to open this issue, as it is a bit unclear.

**Comment by hackyguru** [comment]
the bounty proposal seems to be invalid @Sergei-Mak , i'm closing this issue assuming that it was a mistake. please reopen with fully filled information if you intend to propose a bounty.

also FYI, Waku bounties are paused until further notice.
